import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">LandingCardHolderOne</Link>
        </li>
        <li>
          <Link to="/applycard">ApplyCard</Link>
        </li>
        <li>
          <Link to="/applycardtwo">ApplyCardTwo</Link>
        </li>
        <li>
          <Link to="/landingcardholdertwo">LandingCardHolderTwo</Link>
        </li>
        <li>
          <Link to="/landingcardholderthree">LandingCardHolderThree</Link>
        </li>
        <li>
          <Link to="/landingcardholder">LandingCardHolder</Link>
        </li>
        <li>
          <Link to="/tsione">TSIOne</Link>
        </li>
        <li>
          <Link to="/tsi">TSI</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
